# String Method
text = str(input("Enter a string:"))
# lower()
print(text.lower())
# upper()
print(text.upper())
# capitalize()
print(text.capitalize())
# title()
print(text.title())
# count()
print(text.count("o"))
# find()
print(text.find("t"))
# replace()
print(text.replace("t", "o"))
# startswith()
print(text.startswith("t"))
# endswith()
print(text.endswith("n"))
